/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TCascader: typeof import('tdesign-mobile-vue')['Cascader']
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TCellGroup: typeof import('tdesign-mobile-vue')['CellGroup']
    TCollapse: typeof import('tdesign-mobile-vue')['Collapse']
    TCollapsePanel: typeof import('tdesign-mobile-vue')['CollapsePanel']
    TDateTimePicker: typeof import('tdesign-mobile-vue')['DateTimePicker']
    TDialog: typeof import('tdesign-mobile-vue')['Dialog']
    TFab: typeof import('tdesign-mobile-vue')['Fab']
    TForm: typeof import('tdesign-mobile-vue')['Form']
    TFormItem: typeof import('tdesign-mobile-vue')['FormItem']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TInput: typeof import('tdesign-mobile-vue')['Input']
    TPicker: typeof import('tdesign-mobile-vue')['Picker']
    TPopup: typeof import('tdesign-mobile-vue')['Popup']
    TRadio: typeof import('tdesign-mobile-vue')['Radio']
    TRadioGroup: typeof import('tdesign-mobile-vue')['RadioGroup']
    TRate: typeof import('tdesign-mobile-vue')['Rate']
    TStepper: typeof import('tdesign-mobile-vue')['Stepper']
    TSwipeCell: typeof import('tdesign-mobile-vue')['SwipeCell']
    TSwitch: typeof import('tdesign-mobile-vue')['Switch']
    TTabBar: typeof import('tdesign-mobile-vue')['TabBar']
    TTabBarItem: typeof import('tdesign-mobile-vue')['TabBarItem']
    TTable: typeof import('tdesign-mobile-vue')['Table']
    TTextarea: typeof import('tdesign-mobile-vue')['Textarea']
    TUpload: typeof import('tdesign-mobile-vue')['Upload']
    UserCell: typeof import('./src/components/UserCell.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
